# Generated by Django 6.0.2 on 2026-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
