# Generated by Django 6.0.2 on 2026-02-17 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_article_meta_description_article_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cons',
            field=models.TextField(blank=True, help_text='One con per line'),
        ),
        migrations.AddField(
            model_name='product',
            name='pros',
            field=models.TextField(blank=True, help_text='One pro per line'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='0.0 to 5.0 (use .5 for half stars, e.g. 4.5)', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
