# Generated by Django 6.0.2 on 2026-02-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_product_cons_product_pros_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_image_url',
            field=models.URLField(blank=True, help_text='Set by API later (do not upload Amazon images yourself)'),
        ),
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, db_index=True, help_text='10-char Amazon ASIN', max_length=10),
        ),
    ]
