# Generated by Django 6.0.2 on 2026-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_refresh_june_2026_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visual_type',
            field=models.CharField(choices=[('monitor', 'Monitor'), ('laptop', 'Laptop'), ('storage', 'Storage'), ('accessory', 'Accessory')], default='monitor', max_length=30),
        ),
    ]
